Yuanqing/feature trecord
DLUT-SIE/TMSFTT-BE pull request #13
Opened 2019-01-15 10:57 UTC by Yqzzxlj

Added serializers.py, views.py and tests_serializers.py, test__views.py
Added training_record/urls.py
Added url in TMSFTT/urls.py for training_record

2019-01-16 05:39 UTC, ghh82058 submitted a review, later dismissed

2019-01-16 06:45 UTC, a8520238 submitted a review, later dismissed

2019-01-17 01:32 UTC, Time1ess requested changes

2019-01-17 01:32 UTC, Time1ess commented on TMSFTT/urls.py
> +    path('training_record', include('training_record.urls')),
```suggestion
    path('training-record', include('training_record.urls')),
```
As suggested in https://github.com/DLUT-SIE/TMSFTT-BE/pull/9/files#r248498944

2019-01-17 01:32 UTC, Time1ess commented on training_record/serializers.py
> +class UserSerializer(serializers.ModelSerializer):
Delete this.
As comment at https://github.com/DLUT-SIE/TMSFTT-BE/pull/10/files#r248509481

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_serializers.py
> +class TestUserSerializer(TestCase):
Delete this.

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_serializers.py
> +        recordcontent = models.RecordContent()
```suggestion
        record_content = models.RecordContent()
```

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_serializers.py
> +        recordattachment = models.RecordAttachment()
Ditto.

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_serializers.py
> +        statuschangelog = models.StatusChangeLog()
Ditto.

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_views.py
> +        self.assertEqual(training_record.models.Record.objects.get().
https://github.com/DLUT-SIE/TMSFTT-BE/pull/9/files#r248504817.

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_views.py
> +    def test_create_recordcontent(self):
```suggestion
    def test_create_record_content(self):
```

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_views.py
> +    def test_list_recordcontent(self):
```suggestion
    def test_list_record_content(self):
```

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_views.py
> +        response = self.client.post(url, data, format='multipart')
https://github.com/DLUT-SIE/TMSFTT-BE/pull/10/files#r248511133

2019-01-17 01:32 UTC, Time1ess commented on training_record/tests/tests_views.py
> +        attachment_type = 0
Do not use 0 directly, you can use `RecordAttachment.ATTACHMENT_TYPE_CONTENT` to replace it.

2019-01-17 11:35 UTC, Time1ess approved these changes

2019-01-17 11:35 UTC, Time1ess commented on TMSFTT/urls.py
> +    path('training-record', include('training_record.urls')),
While this is OK, it's better to keep this close to other training* routes, so please move it down.

2019-01-18 02:55 UTC, a8520238 approved these changes

2019-01-18 03:01 UTC, merged