Huihua/feature training review
DLUT-SIE/TMSFTT-BE pull request #14
Opened 2019-01-15 14:27 UTC by ghh82058

2019-01-17 01:34 UTC, Time1ess requested changes
Some duplicates are not commented, please fix them also.

2019-01-17 01:34 UTC, Time1ess commented on TMSFTT/urls.py
> +    path('training_review/', include('training_review.urls'))
```suggestion
    path('training-review/', include('training_review.urls'))
```

2019-01-17 01:34 UTC, Time1ess commented on training_review/tests/tests_views.py
> +        offcampusevent = mommy.make(tevent.OffCampusEvent)
```suggestion
        off_campus_event = mommy.make(tevent.OffCampusEvent)
```

2019-01-17 07:44 UTC, Yqzzxlj approved these changes

2019-01-17 11:29 UTC, Time1ess commented
This branch is outdated, please fetch dev and rebase your branch against dev. @ghh82058

2019-01-18 04:18 UTC, Time1ess approved these changes

2019-01-18 04:36 UTC, merged