lgz/training_program
DLUT-SIE/TMSFTT-BE pull request #9
Opened 2019-01-14 07:38 UTC by a8520238

1th training_program

2019-01-14 07:53 UTC, dutlzn submitted a review, later dismissed

2019-01-15 16:09 UTC, ghh82058 approved these changes

2019-01-16 01:06 UTC, dutlzn approved these changes

2019-01-16 06:22 UTC, ghh82058 reviewed
A few changes.

2019-01-16 06:22 UTC, ghh82058 commented on training_program/urls.py
> +router.register(r'programcategory', training_program.views.
```suggestion
router.register(r'program-categories', training_program.views.
```

2019-01-16 06:22 UTC, ghh82058 commented on training_program/urls.py
> +router.register(r'programform', training_program.views.ProgramFormViewSet)
```suggestion
router.register(r'program-forms', training_program.views.ProgramFormViewSet)
```

2019-01-17 00:54 UTC, Time1ess requested changes
* Variable naming style, like `programcategory` could be `category` given a context.
* Function naming style, like `test_create_programcategory` should be `test_create_program_category`.
* How do we indent codes in Python ? You can refer to [link](https://www.python.org/dev/peps/pep-0008/#indentation).
* Routing naming style. In practice, we use `-`(dash) more, instead of `_`(underscore).

2019-01-17 00:54 UTC, Time1ess commented on TMSFTT/urls.py
> +    path('training_program/', include('training_program.urls')),
```suggestion
    path('training-program/', include('training_program.urls')),
```
I think dash is a better practice than underscore, and sorry for the bad example, I've fixed it.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_serializers.py
> +        programcategory = models.ProgramCategory()
```suggestion
        category = models.ProgramCategory()
```
Given the context, It's ok to name the variable as `category`.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_serializers.py
> +                   (programcategory).data.keys())
```suggestion
                   (category).data.keys())
```
ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_serializers.py
> +        programform = models.ProgramForm()
```suggestion
        form = models.ProgramForm()
```
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_serializers.py
> +        keys = set(serializers.ProgramFormSerializer(programform).data.keys())
```suggestion
        keys = set(serializers.ProgramFormSerializer(form).data.keys())
```
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_serializers.py
> +        expected_keys = models.Program()
```suggestion
```
Unused?

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        self.assertEqual(training_program.models.ProgramCategory.
https://github.com/DLUT-SIE/TMSFTT-BE/blob/24e4155fe4aa1002811d9fefe8a34f04192526e2/training_program/tests/tests_views.py#L22-L23
You can use:
```
self.assertEqual(
    training_program.models.ProgramCategory.objects.count(), 1)
```
or use a parenthesis to wrap your chain calls, like:
```
self.assertEqual((training_program.models.ProgramCategory
                 .objects.count()), 1)
```
Note that we move the dot to the next line and add a `()` to wrap the whole chain call.

IMHO, the former is a better practice, unless your code is too long.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        self.assertEqual(training_program.models.ProgramCategory.objects.
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        self.assertEqual(training_program.models.ProgramForm.objects.get().
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +    def test_create_programcategory(self):
```suggestion
    def test_create_program_category(self):
```

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +    def test_list_programcatgegery(self):
```suggestion
    def test_list_program_catgegery(self):
```

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +    def test_delete_programcategory(self):
```suggestion
    def test_delete_program_category(self):
```

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        self.assertEqual(training_program.models.ProgramCategory.objects.
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        programcategory = mommy.make(training_program.models.ProgramCategory)
```suggestion
        category = mommy.make(training_program.models.ProgramCategory)
```
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        programcategory = mommy.make(training_program.models.ProgramCategory)
```suggestion
        category = mommy.make(training_program.models.ProgramCategory)
```
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        programcategory = mommy.make(training_program.models.ProgramCategory,
```suggestion
        category = mommy.make(training_program.models.ProgramCategory,
```
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        programform = mommy.make(training_program.models.ProgramForm)
```suggestion
        form = mommy.make(training_program.models.ProgramForm)
```
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        self.assertEqual(training_program.models.ProgramForm.objects.count(),
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        programform = mommy.make(training_program.models.ProgramForm)
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +        programform = mommy.make(training_program.models.ProgramForm,
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/tests/tests_views.py
> +    def test_update_programform(self):
Ditto.

2019-01-17 00:54 UTC, Time1ess commented on training_program/urls.py
> +router.register(r'programcategory', training_program.views.
+1

2019-01-17 00:54 UTC, Time1ess commented on training_program/urls.py
> +router.register(r'programform', training_program.views.ProgramFormViewSet)
+1

2019-01-17 08:40 UTC, Time1ess approved these changes

2019-01-17 08:43 UTC, merged